Repository intel-retail/documentation, pull requests merged in 2024-09, with the labels that each got.

#31 fix: Add back scans to documentation repo
  .github/.trivyConf.yaml
  .github/dependabot.yml
  .github/workflows/trivy-scan.yaml
Labels: enhancement

#29 doc: Add troublshooting section
  docs_src/troubleshooting.md
  mkdocs.yml
Labels: documentation, 3.1

#30 Loss prevention
  docs_src/use-cases/loss-prevention/advanced.md
  docs_src/use-cases/loss-prevention/getting_started.md
  docs_src/use-cases/loss-prevention/loss-prevention.md
  mkdocs.yml
Labels: documentation
