Repository intel-retail/documentation, pull requests merged in 2024-10, with the labels that each got.

#35 Docs: Adding class filtering section
  Makefile
  docs_src/use-cases/loss-prevention/advanced.md
Labels: documentation

#37 docs: loss prevention business logic
  docs_src/use-cases/loss-prevention/advanced.md
  docs_src/use-cases/loss-prevention/images/mqtt-diagram.jpg
Labels: documentation, loss-prevention

#36 docs: created documentation for capi yolov8 ensemble k8s
  docs_src/use-cases/capi-yolov8-ensemble/capi-yolov8-ensemble.md
  docs_src/use-cases/capi-yolov8-ensemble/getting_started.md
  docs_src/use-cases/capi-yolov8-ensemble/images/yolov8-efficientnet-profile.jpg
  docs_src/use-cases/use-cases.md
Labels: documentation, 3.2

#39 deploy github pages manually
  .github/workflows/github-pages.yml
Labels: bug
