Repository intel-retail/documentation, pull requests merged in 2024-05, with the labels that each got.

#14 feat: yolov8 + efficientnet profile
  Architecture/images/yolov8-efficientnet-profile.jpg
  Architecture/yolov8-efficientnet-profile.md
Labels: enhancement, 2.1

#21 docs: add API documentation for benchmarking
  Dockerfile.docs
  docs_src/performance-tools/api-docs.md
  mkdocs.yml
Labels: documentation

#23 doc: Update to latest discord invite link
  README.md
  docs/search/search_index.json
  docs/use-cases/automated-self-checkout/getting_started.html
  docs_src/use-cases/automated-self-checkout/getting_started.md
Labels: documentation, 3.0

#24 doc: Update results output
  docs/search/search_index.json
  docs/use-cases/automated-self-checkout/getting_started.html
  docs_src/use-cases/automated-self-checkout/getting_started.md
Labels: documentation, 3.0

#25 doc: Format update for release notes 3.0
  docs/release-notes/v3-0-0.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs_src/release-notes/v3-0-0.md
Labels: documentation, 3.0

#26 docs: integration of AiCSD arch
  docs_src/Architecture/v3.0.0/aicsd-integration.md
  docs_src/Architecture/v3.0.0/images/aicsd-initial-integration.jpg
  mkdocs.yml
Labels: documentation, enhancement

#27 docs: Add docs for grpc-go service
  docs_src/use-cases/AiCSD/aicsd.md
  docs_src/use-cases/AiCSD/pipeline-grpc-go.md
  docs_src/use-cases/use-cases.md
  mkdocs.yml
Labels: documentation
